site_name: Build Tools for Aria Docs
repo_url: https://github.com/vmware/build-tools-for-vmware-aria
docs_dir: mkdocs
# Fail if can not resolve links
strict: true
theme:
  name: material
  logo: assets/logo.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.follow
    - search.highlight
    - search.suggest
    - search.share
    - content.code.annotate
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Dark Mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Light Mode
extra:
  version:
    provider: mike
  iac:
    latest_release: 2.33.0
  general:
    bta_name: Build Tools for VMware Aria
  products:
    vra_8_full_name: vRealize Automation 8.x
    vra_8_short_name: vRA 8
    vra_cloud_short_name: vRA Cloud
  archetype:
    customer_project:
      group_id: com.company.bu
      group_id_hint: The groupId in Maven is a distinctive identifier specifically used for a project. It acts as a namespace, ensuring that project names don't clash with each other. It is recommended to choose a groupId that reflects your organization or project.
      artifact_id: project.type
      artifact_id_hint: The artifactId is a unique identifier for a specific project or module within a project. It represents the name of the artifact that is generated by the project. It is recommended to choose a artifactId that reflects the project type.
      maven_settings_location_hint: The location of *settings.xml* for **macos** is *~/.m2* and *C:\Users\username\\.m2* for **windows**
      maven_profile_name: target-env


plugins:
  - include-markdown
  - search
  - awesome-pages
  - tags
  - macros:
      on_error_fail: true
  - mike:
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
# extra_css:
#   - css/version-select.css
# extra_javascript:
#   - js/version-select.js
