version: "3"
services:
  # NGINX reverse proxy server
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: always
    networks:
      infranet:
        ipv4_address: 172.18.0.10
    ports:
      - "80:80"
      - "443:443"
    hostname: "infra.corp.local"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/certs:/etc/nginx/certs:ro"
      - "./nginx/proxy.conf:/etc/nginx/proxy.conf:ro"
      - "/var/log/nginx:/var/log/nginx"
  # GitLab CE Git repository manager
  gitlab:
    image: gitlab/gitlab-ce:12.10.3-ce.0
    container_name: gitlab-ce
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://infra.corp.local/gitlab"
    networks:
      infranet:
        ipv4_address: 172.18.0.11
    extra_hosts:
      - "infra.corp.local:<DOCKER_HOST_IP>"
    ports:
    - "127.0.0.1:8080:80"
    hostname: "gitlab.corp.local"
    volumes:
      - "gitlab-config:/etc/gitlab"
      - "gitlab-logs:/var/log/gitlab"
      - "gitlab-data:/var/opt/gitlab"
  # GitLab CI Runner for CI/CD integration
  gitlab-runner:
    image: pscoelab/vrbt-gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    hostname: "gitlab-runner.corp.local"
    networks:
      infranet:
        ipv4_address: 172.18.0.12
    extra_hosts:
      - "infra.corp.local:172.18.0.10"
      - "gitlab.corp.local:172.18.0.11"
      - "nexus.corp.local:172.18.0.14"  # Update with Nexus IP
    volumes:
     - "gitlab-runner-config:/etc/gitlab-runner"
     - "gitlab-runner-m2:/home/gitlab-runner/.m2"     
     - "gitlab-runner-opt:/var/opt"     
     - "/var/run/docker.sock:/var/run/docker.sock"
  # Sonatype Nexus for artifact management
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    hostname: "nexus.corp.local"
    networks:
      infranet:
        ipv4_address: 172.18.0.14
    ports:
     - 127.0.0.1:8081:8081
    volumes:
     - "nexus-data:/nexus-data"
    restart: always

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner-config:
  gitlab-runner-m2:
  gitlab-runner-opt:
  nexus-data:

networks:
 infranet:
